server:
  port: '8085'
#  ssl:
#    key-store: springboot.jks
#    key-store-password: password
#    key-store-type: jks
#    key-alias: springboot
#    key-password: password

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pcp
  application:
    name: payment-card-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka