version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27107"
    networks:
      - example
  order-processing:
    build:
      context: ./order-processing
    environment:
      - MONGO_HOST=mongodb
    depends_on:
      - mongodb
    networks:
      - example
    container_name: order-processing

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    networks:
      - example
    environment:
      - MYSQL_DATABASE=backoffice
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
    ports:
      - "3306:3306"
  backoffice:
    build:
      context: ./backoffice
    environment:
      - MYSQL_HOST=mysql
    depends_on:
      - mysql
    networks:
      - example
    container_name: backoffice
    restart: on-failure

  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8081:8081"
    environment:
      - BACK_OFFICE_HOST=backoffice
      - ORDER_PROCESSING_HOST=order-processing
      - ORDER_SEARCH_HOST=order-search
    depends_on:
      - order-processing
      - backoffice
    networks:
      - example


networks:
  example: