server:
  port: 8001
#  ssl:
#    key-store: springboot.jks
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password

spring:
  application:
      name: auth
  mail:
    host: 'smtp.office365.com'
    port: 587
    username: bsep-test@outlook.com
    password: bsep_bsep
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sep
    username: postgres
    password: postgres
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: 'false'
        search:
          default:
            directory_provider: filesystem
            indexBase: ./data/index/default
        format_sql: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'false'
    open-in-view: true
  multipart:
    max-file-size: 100MB
    max-request-size: 100MB
  devtools:
    remote:
      secret: "secret"
  cache:
    jcache:
      config: classpath:ehcache.xml
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  sql:
    init:
      data-locations: classpath:data-postgres.sql
      mode: always
#jpa:
#hibernate:
#dialect: org.hibernate.dialect.PostgreSQL95Dialect
app:
  auth:
    tokenSecret: 124672bc59b44e1f90d5afc5f6c8d500a4713f0eadbc2c1acc2a7caf9c9c9cd8
    tokenExpirationSeconds: 864000
  cors:
    allowedOrigins: http://localhost:4200, http://127.0.0.1:4200, https://localhost:4200, https://127.0.0.1:4200
  mailing:
    templatesLocation: templates
    senderAddress: bsep-test@outlook.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

