server:
  port: '8086'

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/psp
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: psp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
