server:
  port: '8086'
#  ssl:
#    key-store: springboot.jks
#    key-store-password: password
#    key-store-type: jks
#    key-alias: springboot
#    key-password: password

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/psp
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: psp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
