server:
  port: '8444'
  #  ssl:
  #    key-store: springboot.jks
  #    key-store-password: password
  #    key-store-type: pkcs12
  #    key-alias: springboot
  #    key-password: password

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/crypto
      uuid-representation: standard
  application:
    name: crypto
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
