server:
  port: 8081
  
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: CRYPTO-SERVICE
          uri: http://localhost:8444
          predicates:
            - Path=/crypto/api/payment/**
          filters:
            - RewritePath=/crypto/(?<remaining>.*), /${remaining}
        - id: PAYPAL-SERVICE
          uri: http://localhost:8087
          predicates:
            - Path=/paypal/api/payment/**
          filters:
            - RewritePath=/paypal/(?<remaining>.*), /${remaining}
        - id: BANK-SERVICE
          uri: http://localhost:8000
          predicates:
            - Path=/mbank/api/bank/pay/**
          filters:
            - RewritePath=/mbank/(?<remaining>.*), /${remaining}