server:
  port: 8081

spring:
  rabbitmq:
    host: rabbitmq
    password: guest
    port: 15672
    username: guest
    exchange: user.exchange
    queue: user.queue
    routingkey: user.routingkey

clients:
  auth-service:
    host: ${AUTH_SERVICE_HOST:127.0.0.1}
    port: ${AUTH_SERVICE_PORT:8001}
  payment-card-center:
    host: ${PAYMENT_CARD_CENTER_HOST:127.0.0.1}
    port: ${PAYMENT_CARD_CENTER_PORT:8085}
  payment-service-provider:
    host: ${PAYMENT_SERVICE_HOST:127.0.0.1}
    port: ${PAYMENT_SERVICE_PORT:8086}
  paypal-service:
    host: ${PAYPAL_SERVICE_HOST:127.0.0.1}
    port: ${PAYPAL_SERVICE_PORT:8087}


routes-to-add-to-cors-config:
  routes:
    - /api/**