server:
  port: 8081

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: API-GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: CRYPTO-SERVICE
          uri: http://localhost:8444
          predicates:
            - Path=/crypto/api/payment/**
          filters:
            - RewritePath=/crypto/(?<remaining>.*), /$\