server:
  port: '8087'
paypal:
  mode: 'sandbox'
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/paypal
  config:
    import: optional:secrets.properties
  application:
    name: paypal
  devtools:
    restart:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
