server:
  port: '8087'
  #  ssl:
  #    key-store: springboot.jks
  #    key-store-password: password
  #    key-store-type: pkcs12
  #    key-alias: springboot
  #    key-password: password

paypal:
  mode: 'sandbox'
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/paypal
  config:
    import: optional:secrets.properties
  application:
    name: paypal
  devtools:
    restart:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
